# Latihan DataFrame Pandas

In [4]:
import pandas as pd

In [2]:
# Membuat dictionary dengan data mobil
data = {
    'Merk': ['Toyota', 'Honda', 'Mazda', 'Mitsuboshi', 'Ford', 'Toyota', 'Honda', 'Mazda', 'Mitsubishi', 'Ford',
             'Toyota', 'Honda', 'Mazda', 'Mitsubishi', 'Ford', 'Toyota', 'Honda', 'Mazda', 'Mitsubishi', 'Ford'],
    'Model': ['Camry', 'Civic', 'CX-5', 'Lancer', 'Mustang', 'Corolla', 'Accord', 'Mazda3', 'Pajero', 'Explorer',
              'RAV4', 'Fit', 'MX-5', 'Outlander', 'F-150', 'Highlander', 'HR-V', 'CX-9', 'Mirage', 'Bronco'],
    'Tahun': [2020, 2021, 2021, 2020, 2019, 2019, 2020, 2021, 2021, 2020,
              2021, 2019, 2020, 2021, 2020, 2020, 2021, 2019, 2020, 2021],
    'Harga (USD)': [24000, 22000, 28000, 23000, 35000, 20000, 25000, 26000, 21000, 32000,
                    30000, 18000, 27000, 22000, 34000, 31000, 23000, 35000, 17000, 37000],
    'Mesin (L)': [2.5, 2.0, 2.5, 2.0, 5.0, 1.8, 2.4, 2.5, 2.4, 3.5,
                  2.5, 1.5, 2.0, 2.0, 3.5, 3.5, 1.8, 2.5, 1.2, 2.7],
    'Konsumsi Bahan Bakar (MPG)': [28, 32, 29, 27, 22, 30, 28, 31, 26, 24,
                                    31, 33, 28, 29, 20, 24, 32, 26, 34, 21]
}

## 1. Berdasarkan data diatas, buatlah dataframe dengan nama **df**!

In [5]:
# ketikan kode anda disini:
df = pd.DataFrame(data)
df

,Merk,Model,Tahun,Harga (USD),Mesin (L),Konsumsi Bahan Bakar (MPG)
0,Toyota,Camry,2020,24000,2.5,28
1,Honda,Civic,2021,22000,2.0,32
2,Mazda,CX-5,2021,28000,2.5,29
3,Mitsuboshi,Lancer,2020,23000,2.0,27
4,Ford,Mustang,2019,35000,5.0,22
5,Toyota,Corolla,2019,20000,1.8,30
6,Honda,Accord,2020,25000,2.4,28
7,Mazda,Mazda3,2021,26000,2.5,31
8,Mitsubishi,Pajero,2021,21000,2.4,26
9,Ford,Explorer,2020,32000,3.5,24
10,Toyota,RAV4,2021,30000,2.5,31
11,Honda,Fit,2019,18000,1.5,33
12,Mazda,MX-5,2020,27000,2.0,28
13,Mitsubishi,Outlander,2021,22000,2.0,29
14,Ford,F-150,2020,34000,3.5,20
15,Toyota,Highlander,2020,31000,3.5,24
16,Honda,HR-V,2021,23000,1.8,32
17,Mazda,CX-9,2019,35000,2.5,26
18,Mitsubishi,Mirage,2020,17000,1.2,34
19,Ford,Bronco,2021,37000,2.7,21

In [ ]:
# hasil output yang diinginkan:

,Merk,Model,Tahun,Harga (USD),Mesin (L),Konsumsi Bahan Bakar (MPG)
0,Toyota,Camry,2020,24000,2.5,28
1,Honda,Civic,2021,22000,2.0,32
2,Mazda,CX-5,2021,28000,2.5,29
3,Mitsuboshi,Lancer,2020,23000,2.0,27
4,Ford,Mustang,2019,35000,5.0,22
5,Toyota,Corolla,2019,20000,1.8,30
6,Honda,Accord,2020,25000,2.4,28
7,Mazda,Mazda3,2021,26000,2.5,31
8,Mitsubishi,Pajero,2021,21000,2.4,26
9,Ford,Explorer,2020,32000,3.5,24
10,Toyota,RAV4,2021,30000,2.5,31
11,Honda,Fit,2019,18000,1.5,33
12,Mazda,MX-5,2020,27000,2.0,28
13,Mitsubishi,Outlander,2021,22000,2.0,29
14,Ford,F-150,2020,34000,3.5,20
15,Toyota,Highlander,2020,31000,3.5,24
16,Honda,HR-V,2021,23000,1.8,32
17,Mazda,CX-9,2019,35000,2.5,26
18,Mitsubishi,Mirage,2020,17000,1.2,34
19,Ford,Bronco,2021,37000,2.7,21

## 2. Ambil data pada index 10 seperti pada hasil berikut.

In [6]:
# ketikan kode anda disini:
df.loc[10]

Merk                          Toyota
Model                           RAV4
Tahun                           2021
Harga (USD)                    30000
Mesin (L)                        2.5
Konsumsi Bahan Bakar (MPG)        31
Name: 10, dtype: object

In [ ]:
# hasil output yang diinginkan:

Merk                          Toyota
Model                           RAV4
Tahun                           2021
Harga (USD)                    30000
Mesin (L)                        2.5
Konsumsi Bahan Bakar (MPG)        31
Name: 10, dtype: object

## 3. Ubah nama kolom **Konsumsi Bahan Bakar (MPG)** menjadi **MPG** (Gunakan parameter inplace untuk mengubah permanen nama kolom)

In [ ]:
# ketikan kode anda disini:
df.rename(columns={
    'Konsumsi Bahan Bakar (MPG)' : 'MPG'
},
inplace=True
)
df

          Merk       Model  Tahun  Harga (USD)  Mesin (L)  MPG
0       Toyota       Camry   2020        24000        2.5   28
1        Honda       Civic   2021        22000        2.0   32
2        Mazda        CX-5   2021        28000        2.5   29
3   Mitsuboshi      Lancer   2020        23000        2.0   27
4         Ford     Mustang   2019        35000        5.0   22
5       Toyota     Corolla   2019        20000        1.8   30
6        Honda      Accord   2020        25000        2.4   28
7        Mazda      Mazda3   2021        26000        2.5   31
8   Mitsubishi      Pajero   2021        21000        2.4   26
9         Ford    Explorer   2020        32000        3.5   24
10      Toyota        RAV4   2021        30000        2.5   31
11       Honda         Fit   2019        18000        1.5   33
12       Mazda        MX-5   2020        27000        2.0   28
13  Mitsubishi   Outlander   2021        22000        2.0   29
14        Ford       F-150   2020        34000        3.5   20
15      Toyota  Highlander   2020        31000        3.5   24
16       Honda        HR-V   2021        23000        1.8   32
17       Mazda        CX-9   2019        35000        2.5   26
18  Mitsubishi      Mirage   2020        17000        1.2   34
19        Ford      Bronco   2021        37000        2.7   21

In [ ]:
# hasil output yang diinginkan:

          Merk       Model  Tahun  Harga (USD)  Mesin (L)  MPG
0       Toyota       Camry   2020        24000        2.5   28
1        Honda       Civic   2021        22000        2.0   32
2        Mazda        CX-5   2021        28000        2.5   29
3   Mitsuboshi      Lancer   2020        23000        2.0   27
4         Ford     Mustang   2019        35000        5.0   22
5       Toyota     Corolla   2019        20000        1.8   30
6        Honda      Accord   2020        25000        2.4   28
7        Mazda      Mazda3   2021        26000        2.5   31
8   Mitsubishi      Pajero   2021        21000        2.4   26
9         Ford    Explorer   2020        32000        3.5   24
10      Toyota        RAV4   2021        30000        2.5   31
11       Honda         Fit   2019        18000        1.5   33
12       Mazda        MX-5   2020        27000        2.0   28
13  Mitsubishi   Outlander   2021        22000        2.0   29
14        Ford       F-150   2020        34000        3.5   20
15      Toyota  Highlander   2020        31000        3.5   24
16       Honda        HR-V   2021        23000        1.8   32
17       Mazda        CX-9   2019        35000        2.5   26
18  Mitsubishi      Mirage   2020        17000        1.2   34
19        Ford      Bronco   2021        37000        2.7   21

## 4. Perbaiki kesalahan penulisan kata **Mitsubhosi** yang ada pada dataframe menjadi **Mitsubishi**!

In [ ]:
# ketikan kode anda disini:
df.loc[3, 'Merk'] = 'Mitsubishi'
df

          Merk       Model  Tahun  Harga (USD)  Mesin (L)  MPG
0       Toyota       Camry   2020        24000        2.5   28
1        Honda       Civic   2021        22000        2.0   32
2        Mazda        CX-5   2021        28000        2.5   29
3   Mitsubishi      Lancer   2020        23000        2.0   27
4         Ford     Mustang   2019        35000        5.0   22
5       Toyota     Corolla   2019        20000        1.8   30
6        Honda      Accord   2020        25000        2.4   28
7        Mazda      Mazda3   2021        26000        2.5   31
8   Mitsubishi      Pajero   2021        21000        2.4   26
9         Ford    Explorer   2020        32000        3.5   24
10      Toyota        RAV4   2021        30000        2.5   31
11       Honda         Fit   2019        18000        1.5   33
12       Mazda        MX-5   2020        27000        2.0   28
13  Mitsubishi   Outlander   2021        22000        2.0   29
14        Ford       F-150   2020        34000        3.5   20
15      Toyota  Highlander   2020        31000        3.5   24
16       Honda        HR-V   2021        23000        1.8   32
17       Mazda        CX-9   2019        35000        2.5   26
18  Mitsubishi      Mirage   2020        17000        1.2   34
19        Ford      Bronco   2021        37000        2.7   21

In [ ]:
# hasil output yang diinginkan:

          Merk       Model  Tahun  Harga (USD)  Mesin (L)  MPG
0       Toyota       Camry   2020        24000        2.5   28
1        Honda       Civic   2021        22000        2.0   32
2        Mazda        CX-5   2021        28000        2.5   29
3   Mitsubishi      Lancer   2020        23000        2.0   27
4         Ford     Mustang   2019        35000        5.0   22
5       Toyota     Corolla   2019        20000        1.8   30
6        Honda      Accord   2020        25000        2.4   28
7        Mazda      Mazda3   2021        26000        2.5   31
8   Mitsubishi      Pajero   2021        21000        2.4   26
9         Ford    Explorer   2020        32000        3.5   24
10      Toyota        RAV4   2021        30000        2.5   31
11       Honda         Fit   2019        18000        1.5   33
12       Mazda        MX-5   2020        27000        2.0   28
13  Mitsubishi   Outlander   2021        22000        2.0   29
14        Ford       F-150   2020        34000        3.5   20
15      Toyota  Highlander   2020        31000        3.5   24
16       Honda        HR-V   2021        23000        1.8   32
17       Mazda        CX-9   2019        35000        2.5   26
18  Mitsubishi      Mirage   2020        17000        1.2   34
19        Ford      Bronco   2021        37000        2.7   21

## 5. Tambahkan kolom warna pada dataframe df (data warna bebas)

In [10]:
# ketikan kode anda disini:
df['Warna'] = 'Biru'
df

          Merk       Model  Tahun  Harga (USD)  Mesin (L)  MPG Warna
0       Toyota       Camry   2020        24000        2.5   28  Biru
1        Honda       Civic   2021        22000        2.0   32  Biru
2        Mazda        CX-5   2021        28000        2.5   29  Biru
3   Mitsubishi      Lancer   2020        23000        2.0   27  Biru
4         Ford     Mustang   2019        35000        5.0   22  Biru
5       Toyota     Corolla   2019        20000        1.8   30  Biru
6        Honda      Accord   2020        25000        2.4   28  Biru
7        Mazda      Mazda3   2021        26000        2.5   31  Biru
8   Mitsubishi      Pajero   2021        21000        2.4   26  Biru
9         Ford    Explorer   2020        32000        3.5   24  Biru
10      Toyota        RAV4   2021        30000        2.5   31  Biru
11       Honda         Fit   2019        18000        1.5   33  Biru
12       Mazda        MX-5   2020        27000        2.0   28  Biru
13  Mitsubishi   Outlander   2021        22000        2.0   29  Biru
14        Ford       F-150   2020        34000        3.5   20  Biru
15      Toyota  Highlander   2020        31000        3.5   24  Biru
16       Honda        HR-V   2021        23000        1.8   32  Biru
17       Mazda        CX-9   2019        35000        2.5   26  Biru
18  Mitsubishi      Mirage   2020        17000        1.2   34  Biru
19        Ford      Bronco   2021        37000        2.7   21  Biru

In [ ]:
# hasil output yang diinginkan:

          Merk       Model  Tahun  Harga (USD)  Mesin (L)  MPG Warna
0       Toyota       Camry   2020        24000        2.5   28  Biru
1        Honda       Civic   2021        22000        2.0   32  Biru
2        Mazda        CX-5   2021        28000        2.5   29  Biru
3   Mitsubishi      Lancer   2020        23000        2.0   27  Biru
4         Ford     Mustang   2019        35000        5.0   22  Biru
5       Toyota     Corolla   2019        20000        1.8   30  Biru
6        Honda      Accord   2020        25000        2.4   28  Biru
7        Mazda      Mazda3   2021        26000        2.5   31  Biru
8   Mitsubishi      Pajero   2021        21000        2.4   26  Biru
9         Ford    Explorer   2020        32000        3.5   24  Biru
10      Toyota        RAV4   2021        30000        2.5   31  Biru
11       Honda         Fit   2019        18000        1.5   33  Biru
12       Mazda        MX-5   2020        27000        2.0   28  Biru
13  Mitsubishi   Outlander   2021        22000        2.0   29  Biru
14        Ford       F-150   2020        34000        3.5   20  Biru
15      Toyota  Highlander   2020        31000        3.5   24  Biru
16       Honda        HR-V   2021        23000        1.8   32  Biru
17       Mazda        CX-9   2019        35000        2.5   26  Biru
18  Mitsubishi      Mirage   2020        17000        1.2   34  Biru
19        Ford      Bronco   2021        37000        2.7   21  Biru

## 6. Buatlah kolom baru yaitu **Merk Model** yang merupakan gabungan kolom Merk dan Model!

In [11]:
# ketikan kode anda disini:
df['Merk Model'] = df['Merk'] + ' ' + df['Model']
df

,Merk,Model,Tahun,Harga (USD),Mesin (L),MPG,Warna,Merk Model
0,Toyota,Camry,2020,24000,2.5,28,Biru,Toyota Camry
1,Honda,Civic,2021,22000,2.0,32,Biru,Honda Civic
2,Mazda,CX-5,2021,28000,2.5,29,Biru,Mazda CX-5
3,Mitsubishi,Lancer,2020,23000,2.0,27,Biru,Mitsubishi Lancer
4,Ford,Mustang,2019,35000,5.0,22,Biru,Ford Mustang
5,Toyota,Corolla,2019,20000,1.8,30,Biru,Toyota Corolla
6,Honda,Accord,2020,25000,2.4,28,Biru,Honda Accord
7,Mazda,Mazda3,2021,26000,2.5,31,Biru,Mazda Mazda3
8,Mitsubishi,Pajero,2021,21000,2.4,26,Biru,Mitsubishi Pajero
9,Ford,Explorer,2020,32000,3.5,24,Biru,Ford Explorer
10,Toyota,RAV4,2021,30000,2.5,31,Biru,Toyota RAV4
11,Honda,Fit,2019,18000,1.5,33,Biru,Honda Fit
12,Mazda,MX-5,2020,27000,2.0,28,Biru,Mazda MX-5
13,Mitsubishi,Outlander,2021,22000,2.0,29,Biru,Mitsubishi Outlander
14,Ford,F-150,2020,34000,3.5,20,Biru,Ford F-150
15,Toyota,Highlander,2020,31000,3.5,24,Biru,Toyota Highlander
16,Honda,HR-V,2021,23000,1.8,32,Biru,Honda HR-V
17,Mazda,CX-9,2019,35000,2.5,26,Biru,Mazda CX-9
18,Mitsubishi,Mirage,2020,17000,1.2,34,Biru,Mitsubishi Mirage
19,Ford,Bronco,2021,37000,2.7,21,Biru,Ford Bronco

In [ ]:
# hasil output yang diinginkan:

,Merk,Model,Tahun,Harga (USD),Mesin (L),MPG,Warna,Merk Model
0,Toyota,Camry,2020,24000,2.5,28,Biru,Toyota Camry
1,Honda,Civic,2021,22000,2.0,32,Biru,Honda Civic
2,Mazda,CX-5,2021,28000,2.5,29,Biru,Mazda CX-5
3,Mitsubishi,Lancer,2020,23000,2.0,27,Biru,Mitsubishi Lancer
4,Ford,Mustang,2019,35000,5.0,22,Biru,Ford Mustang
5,Toyota,Corolla,2019,20000,1.8,30,Biru,Toyota Corolla
6,Honda,Accord,2020,25000,2.4,28,Biru,Honda Accord
7,Mazda,Mazda3,2021,26000,2.5,31,Biru,Mazda Mazda3
8,Mitsubishi,Pajero,2021,21000,2.4,26,Biru,Mitsubishi Pajero
9,Ford,Explorer,2020,32000,3.5,24,Biru,Ford Explorer
10,Toyota,RAV4,2021,30000,2.5,31,Biru,Toyota RAV4
11,Honda,Fit,2019,18000,1.5,33,Biru,Honda Fit
12,Mazda,MX-5,2020,27000,2.0,28,Biru,Mazda MX-5
13,Mitsubishi,Outlander,2021,22000,2.0,29,Biru,Mitsubishi Outlander
14,Ford,F-150,2020,34000,3.5,20,Biru,Ford F-150
15,Toyota,Highlander,2020,31000,3.5,24,Biru,Toyota Highlander
16,Honda,HR-V,2021,23000,1.8,32,Biru,Honda HR-V
17,Mazda,CX-9,2019,35000,2.5,26,Biru,Mazda CX-9
18,Mitsubishi,Mirage,2020,17000,1.2,34,Biru,Mitsubishi Mirage
19,Ford,Bronco,2021,37000,2.7,21,Biru,Ford Bronco

## 7. Hapus kolom **warna** dan **Merk Model** yang barusan dibuat!

In [12]:
# ketikan kode anda disini:
df.drop(columns=['Warna', 'Merk Model'], axis = 1, inplace=True)
df

          Merk       Model  Tahun  Harga (USD)  Mesin (L)  MPG
0       Toyota       Camry   2020        24000        2.5   28
1        Honda       Civic   2021        22000        2.0   32
2        Mazda        CX-5   2021        28000        2.5   29
3   Mitsubishi      Lancer   2020        23000        2.0   27
4         Ford     Mustang   2019        35000        5.0   22
5       Toyota     Corolla   2019        20000        1.8   30
6        Honda      Accord   2020        25000        2.4   28
7        Mazda      Mazda3   2021        26000        2.5   31
8   Mitsubishi      Pajero   2021        21000        2.4   26
9         Ford    Explorer   2020        32000        3.5   24
10      Toyota        RAV4   2021        30000        2.5   31
11       Honda         Fit   2019        18000        1.5   33
12       Mazda        MX-5   2020        27000        2.0   28
13  Mitsubishi   Outlander   2021        22000        2.0   29
14        Ford       F-150   2020        34000        3.5   20
15      Toyota  Highlander   2020        31000        3.5   24
16       Honda        HR-V   2021        23000        1.8   32
17       Mazda        CX-9   2019        35000        2.5   26
18  Mitsubishi      Mirage   2020        17000        1.2   34
19        Ford      Bronco   2021        37000        2.7   21

In [ ]:
# hasil output yang diinginkan:

          Merk       Model  Tahun  Harga (USD)  Mesin (L)  MPG
0       Toyota       Camry   2020        24000        2.5   28
1        Honda       Civic   2021        22000        2.0   32
2        Mazda        CX-5   2021        28000        2.5   29
3   Mitsubishi      Lancer   2020        23000        2.0   27
4         Ford     Mustang   2019        35000        5.0   22
5       Toyota     Corolla   2019        20000        1.8   30
6        Honda      Accord   2020        25000        2.4   28
7        Mazda      Mazda3   2021        26000        2.5   31
8   Mitsubishi      Pajero   2021        21000        2.4   26
9         Ford    Explorer   2020        32000        3.5   24
10      Toyota        RAV4   2021        30000        2.5   31
11       Honda         Fit   2019        18000        1.5   33
12       Mazda        MX-5   2020        27000        2.0   28
13  Mitsubishi   Outlander   2021        22000        2.0   29
14        Ford       F-150   2020        34000        3.5   20
15      Toyota  Highlander   2020        31000        3.5   24
16       Honda        HR-V   2021        23000        1.8   32
17       Mazda        CX-9   2019        35000        2.5   26
18  Mitsubishi      Mirage   2020        17000        1.2   34
19        Ford      Bronco   2021        37000        2.7   21

## 8. Buatlah data frame baru berisi satu kolom dengan nama kolom **Negara Produksi**, sesuai dengan list berikut dibawah, beri nama df2!

In [14]:
negara= ['Jepang', 'Jepang', 'Jepang', 'Jepang', 'Amerika Serikat', 'Jepang', 'Jepang', 'Jepang', 'Jepang', 'Amerika Serikat',
                        'Jepang', 'Jepang', 'Jepang', 'Jepang', 'Amerika Serikat', 'Jepang', 'Jepang', 'Jepang', 'Jepang', 'Amerika Serikat']

In [15]:
# ketikan kode anda disini:

df2 = pd.DataFrame(negara, columns=["Negara produksi"])
df2

    Negara produksi
0            Jepang
1            Jepang
2            Jepang
3            Jepang
4   Amerika Serikat
5            Jepang
6            Jepang
7            Jepang
8            Jepang
9   Amerika Serikat
10           Jepang
11           Jepang
12           Jepang
13           Jepang
14  Amerika Serikat
15           Jepang
16           Jepang
17           Jepang
18           Jepang
19  Amerika Serikat

In [ ]:
# hasil output yang diinginkan:

    Negara Produksi
0            Jepang
1            Jepang
2            Jepang
3            Jepang
4   Amerika Serikat
5            Jepang
6            Jepang
7            Jepang
8            Jepang
9   Amerika Serikat
10           Jepang
11           Jepang
12           Jepang
13           Jepang
14  Amerika Serikat
15           Jepang
16           Jepang
17           Jepang
18           Jepang
19  Amerika Serikat

## 9. Gabungkan dataframe df1 dan df2, dimana df2 merupakan kolom negara asal mobil diproduksi!

In [16]:
# ketikan kode anda disini:
gabungan = pd.concat([df, df2], axis=1)
gabungan

,Merk,Model,Tahun,Harga (USD),Mesin (L),MPG,Negara produksi
0,Toyota,Camry,2020,24000,2.5,28,Jepang
1,Honda,Civic,2021,22000,2.0,32,Jepang
2,Mazda,CX-5,2021,28000,2.5,29,Jepang
3,Mitsubishi,Lancer,2020,23000,2.0,27,Jepang
4,Ford,Mustang,2019,35000,5.0,22,Amerika Serikat
5,Toyota,Corolla,2019,20000,1.8,30,Jepang
6,Honda,Accord,2020,25000,2.4,28,Jepang
7,Mazda,Mazda3,2021,26000,2.5,31,Jepang
8,Mitsubishi,Pajero,2021,21000,2.4,26,Jepang
9,Ford,Explorer,2020,32000,3.5,24,Amerika Serikat
10,Toyota,RAV4,2021,30000,2.5,31,Jepang
11,Honda,Fit,2019,18000,1.5,33,Jepang
12,Mazda,MX-5,2020,27000,2.0,28,Jepang
13,Mitsubishi,Outlander,2021,22000,2.0,29,Jepang
14,Ford,F-150,2020,34000,3.5,20,Amerika Serikat
15,Toyota,Highlander,2020,31000,3.5,24,Jepang
16,Honda,HR-V,2021,23000,1.8,32,Jepang
17,Mazda,CX-9,2019,35000,2.5,26,Jepang
18,Mitsubishi,Mirage,2020,17000,1.2,34,Jepang
19,Ford,Bronco,2021,37000,2.7,21,Amerika Serikat

In [ ]:
# hasil output yang diinginkan:

,Merk,Model,Tahun,Harga (USD),Mesin (L),MPG,Negara Produksi
0,Toyota,Camry,2020,24000,2.5,28,Jepang
1,Honda,Civic,2021,22000,2.0,32,Jepang
2,Mazda,CX-5,2021,28000,2.5,29,Jepang
3,Mitsubishi,Lancer,2020,23000,2.0,27,Jepang
4,Ford,Mustang,2019,35000,5.0,22,Amerika Serikat
5,Toyota,Corolla,2019,20000,1.8,30,Jepang
6,Honda,Accord,2020,25000,2.4,28,Jepang
7,Mazda,Mazda3,2021,26000,2.5,31,Jepang
8,Mitsubishi,Pajero,2021,21000,2.4,26,Jepang
9,Ford,Explorer,2020,32000,3.5,24,Amerika Serikat
10,Toyota,RAV4,2021,30000,2.5,31,Jepang
11,Honda,Fit,2019,18000,1.5,33,Jepang
12,Mazda,MX-5,2020,27000,2.0,28,Jepang
13,Mitsubishi,Outlander,2021,22000,2.0,29,Jepang
14,Ford,F-150,2020,34000,3.5,20,Amerika Serikat
15,Toyota,Highlander,2020,31000,3.5,24,Jepang
16,Honda,HR-V,2021,23000,1.8,32,Jepang
17,Mazda,CX-9,2019,35000,2.5,26,Jepang
18,Mitsubishi,Mirage,2020,17000,1.2,34,Jepang
19,Ford,Bronco,2021,37000,2.7,21,Amerika Serikat

## 10. Buatlah dataframe dengan nama **df_pemilik** berdasarkan data dibawah, isi dataframe berasal dari dictionary dengan nama **pemilik_mobil** dan index dari list dengan nama **index_mobil**!

In [18]:
pemilik_mobil = {
    'Nama' : ['Diana', 'Siska', 'Ben', 'Nuri', 'Wahyu'],
}
index_mobil = [2,5,14,2,6]

In [19]:
# ketikan kode anda disini:
df_pemilik = pd.DataFrame(pemilik_mobil, index=index_mobil)
df_pemilik

     Nama
2   Diana
5   Siska
14    Ben
2    Nuri
6   Wahyu

In [ ]:
# hasil output yang diinginkan:

     Nama
2   Diana
5   Siska
14    Ben
2    Nuri
6   Wahyu

## 11. Gunakan penggabungan berdasarkan index untuk mengetahui informasi lengkap dari mobil yang dimililki oleh masing-masing kolom nama!

In [20]:
# ketikan kode anda disini:
df_baru = df_pemilik.join(df, how='inner')
df_baru = df_baru.sort_index()
df_baru.index.name = "Index Mobil"
df_baru

              Nama    Merk    Model  Tahun  Harga (USD)  Mesin (L)  MPG
Index Mobil
2            Diana   Mazda     CX-5   2021        28000        2.5   29
2             Nuri   Mazda     CX-5   2021        28000        2.5   29
5            Siska  Toyota  Corolla   2019        20000        1.8   30
6            Wahyu   Honda   Accord   2020        25000        2.4   28
14             Ben    Ford    F-150   2020        34000        3.5   20

In [ ]:
# hasil output yang diinginkan:

              Nama    Merk    Model  Tahun  Harga (USD)  Mesin (L)  MPG
Index Mobil
2            Diana   Mazda     CX-5   2021        28000        2.5   29
2             Nuri   Mazda     CX-5   2021        28000        2.5   29
5            Siska  Toyota  Corolla   2019        20000        1.8   30
6            Wahyu   Honda   Accord   2020        25000        2.4   28
14             Ben    Ford    F-150   2020        34000        3.5   20